export const ENTERPRISE_ROLES = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  ORGANIZATION_ADMIN: 'ORGANIZATION_ADMIN',
  RECRUITER: 'RECRUITER',
  INTERVIEWER: 'INTERVIEWER',
  HIRING_MANAGER: 'HIRING_MANAGER',
  CANDIDATE: 'CANDIDATE',
} as const;

export const PERMISSIONS = {
  JOBS_CREATE: 'jobs.create',
  JOBS_UPDATE: 'jobs.update',
  JOBS_DELETE: 'jobs.delete',
  JOBS_VIEW: 'jobs.view',
  CANDIDATES_CREATE: 'candidates.create',
  CANDIDATES_VIEW: 'candidates.view',
  CANDIDATES_INVITE: 'candidates.invite',
  INTERVIEWS_CREATE: 'interviews.create',
  INTERVIEWS_START: 'interviews.start',
  INTERVIEWS_REVIEW: 'interviews.review',
  SCORECARDS_CREATE: 'scorecards.create',
  SCORECARDS_APPROVE: 'scorecards.approve',
  ORGANIZATION_MANAGE_USERS: 'organization.manage_users',
  SETTINGS_MANAGE: 'settings.manage',
} as const;

const ALL = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  PLATFORM_ADMIN: ALL,
  ORGANIZATION_ADMIN: [
    PERMISSIONS.ORGANIZATION_MANAGE_USERS,
    PERMISSIONS.SETTINGS_MANAGE,
    ...ALL.filter((permission) => permission !== PERMISSIONS.SETTINGS_MANAGE),
  ],
  RECRUITER: [
    PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_UPDATE,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.CANDIDATES_CREATE,
    PERMISSIONS.CANDIDATES_VIEW,
    PERMISSIONS.CANDIDATES_INVITE,
  ],
  INTERVIEWER: [
    PERMISSIONS.INTERVIEWS_START,
    PERMISSIONS.INTERVIEWS_REVIEW,
    PERMISSIONS.SCORECARDS_CREATE,
  ],
  HIRING_MANAGER: [
    PERMISSIONS.CANDIDATES_VIEW,
    PERMISSIONS.INTERVIEWS_REVIEW,
    PERMISSIONS.SCORECARDS_APPROVE,
  ],
  CANDIDATE: [],
};
