export const Permissions = {
  OrganizationRead: "organization.read",
  OrganizationManage: "organization.manage",
  OrganizationManageUsers: "organization.manage_users",
  SettingsManage: "settings.manage",
  JobRead: "job.read",
  JobCreate: "job.create",
  JobEdit: "job.edit",
  CandidateRead: "candidate.read",
  CandidateContact: "candidate.contact",
  CandidateMoveStage: "candidate.move_stage",
  CandidateScore: "candidate.score",
  SourcingRun: "sourcing.run",
  TalentManage: "talent.manage",
  ScreeningManage: "screening.manage",
  SchedulingManage: "scheduling.manage",
  KnowledgeManage: "knowledge.manage",
  InterviewRead: "interview.read",
  InterviewManage: "interview.manage",
  InterviewEvaluate: "interview.evaluate",
  AssessmentRead: "assessment.read",
  AssessmentManage: "assessment.manage",
  AnalyticsRead: "analytics.read",
  PrivacyManage: "privacy.manage",
  DecisionSubmit: "decision.submit",
  IntegrationManage: "integration.manage",
  AuditRead: "audit.read",
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
