import type { AppLocale } from "./i18n";

export const candidateInterviewUiCopy = {
  en: {
    eyebrow: "Secure AI interview",
    title: "Your interview is ready for the Realtime stage",
    hello: "Hello",
    role: "Role",
    secureSession: "Secure candidate session",
    sessionValidUntil: "Session valid until",
    privacyLine: "Your camera and microphone are used only for this interview. No biometric or emotion inference is performed.",
    stage: {
      localPreview: "Local preview",
      previewPrivate: "Preview stays in this browser until a secure realtime connection is established.",
      cameraOff: "Camera is off",
      audioOnly: "Audio-only mode",
      waiting: "Waiting to start",
      permissions: "Waiting for device permissions",
      ready: "Ready to connect",
      connecting: "Connecting securely…",
      live: "Interview live",
      reconnecting: "Reconnecting…",
      offline: "Connection lost",
      degraded: "Interview paused safely",
      fatal: "Interview cannot continue",
      completed: "Interview completed",
    },
    network: {
      online: "Network is ready.",
      offline: "Network connection is offline. Your secure session is preserved.",
      restored: "Network connection restored. Your secure session is preserved.",
    },
    permissions: {
      title: "Camera & microphone",
      description: "Enable devices here before starting. Permission can be changed later without ending your secure session.",
      microphone: "Microphone",
      camera: "Camera",
      unknown: "Not checked",
      prompt: "Permission needed",
      granted: "Ready",
      denied: "Blocked",
      unavailable: "Unavailable",
      enableBoth: "Enable camera and microphone",
      retryBoth: "Check permissions again",
      checking: "Checking devices…",
      tryAudioOnly: "Try audio-only",
      audioOnlyActive: "Audio-only fallback is active. Camera remains off.",
      microphoneRequired: "A working microphone is required for the spoken interview.",
      deniedHelp: "Browser permission was denied. Allow access in site settings and try again, or use audio-only if only the camera is blocked.",
      unavailableHelp: "The requested device is not available. Check the device connection or try audio-only.",
    },
    controls: {
      microphoneOn: "Mute microphone",
      microphoneOff: "Unmute microphone",
      cameraOn: "Turn camera off",
      cameraOff: "Turn camera on",
      checkRuntime: "Check realtime availability",
      start: "Start interview",
      reconnect: "Reconnect now",
      retry: "Try again",
      backToSetup: "Back to readiness check",
      signInAgain: "Open secure invitation",
    },
    connection: {
      title: "Connection",
      browser: "Browser",
      devices: "Devices",
      realtime: "Realtime service",
      connected: "Connected",
      notConnected: "Not connected",
      available: "Available",
      pending: "Pending activation",
      attempt: "Reconnect attempt",
      runtimePending: "The candidate realtime runtime is not enabled for this deployment yet. No fake live connection is shown.",
      runtimePreserved: "Your authenticated session and saved consent remain intact. You can safely retry this page when realtime is available.",
      reconnecting: "The connection dropped. Your interview state is preserved while the secure transport reconnects.",
      reconnectExhausted: "Automatic retries are exhausted. Nothing has been submitted twice; keep this session and resume when connectivity is stable.",
    },
    fallback: {
      title: "Safe fallback",
      audioOnlyTitle: "Continue without video",
      audioOnlyDescription: "If the camera is blocked but the microphone works, you can prepare in audio-only mode. The runtime still has to pass server-side preflight before the interview can go live.",
      resumeTitle: "Resume later with this secure session",
      resumeDescription: "Do not create a second interview. Your current candidate session is preserved; retry this page or return to the readiness check.",
    },
    error: {
      permission_denied: "Camera or microphone permission is blocked.",
      device_unavailable: "A required media device is unavailable.",
      network_offline: "Your network connection is offline.",
      runtime_unavailable: "Realtime interview service is not available yet.",
      transport_timeout: "The secure connection timed out.",
      transport_unavailable: "The secure connection was interrupted.",
      reconnect_exhausted: "The interview could not reconnect after the allowed attempts.",
      session_expired: "Your secure candidate session has expired.",
      consent_required: "Required interview consent is no longer active.",
      unexpected: "The interview connection encountered an unexpected error.",
    },
    instructionsTitle: "During the interview",
    instructions: [
      "Stay on this page while an answer is being captured or the connection is recovering.",
      "If the network drops, do not start a second interview; reconnect to the same secure session.",
      "You can ask for clarification or decline a question. Final hiring authority remains human.",
    ],
  },
  fa: {
    eyebrow: "مصاحبه امن هوش مصنوعی",
    title: "مصاحبه شما برای مرحله Realtime آماده است",
    hello: "سلام",
    role: "موقعیت شغلی",
    secureSession: "نشست امن کاندیدا",
    sessionValidUntil: "اعتبار نشست تا",
    privacyLine: "دوربین و میکروفن فقط برای همین مصاحبه استفاده می‌شوند و هیچ استنباط بیومتریک یا احساسی انجام نمی‌شود.",
    stage: {
      localPreview: "پیش‌نمایش محلی",
      previewPrivate: "تا قبل از برقراری اتصال امن Realtime، این پیش‌نمایش فقط داخل مرورگر شما می‌ماند.",
      cameraOff: "دوربین خاموش است",
      audioOnly: "حالت فقط صوت",
      waiting: "در انتظار شروع",
      permissions: "در انتظار مجوز دستگاه‌ها",
      ready: "آماده اتصال",
      connecting: "در حال اتصال امن…",
      live: "مصاحبه در حال اجرا",
      reconnecting: "در حال اتصال مجدد…",
      offline: "ارتباط قطع شده",
      degraded: "مصاحبه با حفظ ایمنی متوقف شده",
      fatal: "ادامه مصاحبه ممکن نیست",
      completed: "مصاحبه تکمیل شد",
    },
    network: {
      online: "شبکه آماده است.",
      offline: "ارتباط شبکه قطع شده است. نشست امن شما حفظ می‌شود.",
      restored: "ارتباط شبکه برقرار شد. نشست امن شما حفظ شده است.",
    },
    permissions: {
      title: "دوربین و میکروفن",
      description: "قبل از شروع، دستگاه‌ها را اینجا فعال کنید. تغییر مجوزها نشست امن شما را پایان نمی‌دهد.",
      microphone: "میکروفن",
      camera: "دوربین",
      unknown: "بررسی نشده",
      prompt: "نیازمند مجوز",
      granted: "آماده",
      denied: "مسدود",
      unavailable: "در دسترس نیست",
      enableBoth: "فعال‌کردن دوربین و میکروفن",
      retryBoth: "بررسی دوباره مجوزها",
      checking: "در حال بررسی دستگاه‌ها…",
      tryAudioOnly: "تلاش در حالت فقط صوت",
      audioOnlyActive: "fallback فقط صوت فعال است و دوربین خاموش می‌ماند.",
      microphoneRequired: "برای مصاحبه صوتی، میکروفن سالم و در دسترس الزامی است.",
      deniedHelp: "مجوز مرورگر رد شده است. دسترسی سایت را در تنظیمات مرورگر فعال کنید یا اگر فقط دوربین مسدود است حالت صوتی را امتحان کنید.",
      unavailableHelp: "دستگاه موردنیاز در دسترس نیست. اتصال دستگاه را بررسی کنید یا حالت فقط صوت را امتحان کنید.",
    },
    controls: {
      microphoneOn: "بی‌صدا کردن میکروفن",
      microphoneOff: "فعال کردن میکروفن",
      cameraOn: "خاموش کردن دوربین",
      cameraOff: "روشن کردن دوربین",
      checkRuntime: "بررسی دسترسی Realtime",
      start: "شروع مصاحبه",
      reconnect: "اتصال مجدد",
      retry: "تلاش دوباره",
      backToSetup: "بازگشت به بررسی آمادگی",
      signInAgain: "بازکردن دعوت‌نامه امن",
    },
    connection: {
      title: "وضعیت اتصال",
      browser: "مرورگر",
      devices: "دستگاه‌ها",
      realtime: "سرویس Realtime",
      connected: "متصل",
      notConnected: "متصل نیست",
      available: "در دسترس",
      pending: "در انتظار فعال‌سازی",
      attempt: "تلاش اتصال مجدد",
      runtimePending: "runtime مخصوص کاندیدا در این deployment هنوز فعال نشده است و هیچ اتصال ساختگی به‌عنوان Live نمایش داده نمی‌شود.",
      runtimePreserved: "احراز هویت و رضایت ذخیره‌شده شما حفظ شده است و پس از آماده‌شدن Realtime می‌توانید همین صفحه را دوباره امتحان کنید.",
      reconnecting: "ارتباط قطع شده است. وضعیت مصاحبه تا زمان اتصال مجدد transport امن حفظ می‌شود.",
      reconnectExhausted: "تعداد تلاش‌های اتصال مجدد تمام شده است. هیچ پاسخ یا رویدادی دوبار ثبت نمی‌شود؛ همین نشست را برای ادامه بعدی نگه دارید.",
    },
    fallback: {
      title: "Fallback امن",
      audioOnlyTitle: "ادامه بدون تصویر",
      audioOnlyDescription: "اگر دوربین مسدود است ولی میکروفن کار می‌کند، می‌توانید در حالت فقط صوت آماده شوید. شروع واقعی همچنان به preflight سمت سرور نیاز دارد.",
      resumeTitle: "ادامه بعدی با همین نشست امن",
      resumeDescription: "مصاحبه دوم ایجاد نکنید. نشست فعلی حفظ می‌شود؛ همین صفحه را دوباره امتحان کنید یا به بررسی آمادگی برگردید.",
    },
    error: {
      permission_denied: "مجوز دوربین یا میکروفن مسدود است.",
      device_unavailable: "یکی از دستگاه‌های رسانه‌ای موردنیاز در دسترس نیست.",
      network_offline: "ارتباط شبکه شما قطع است.",
      runtime_unavailable: "سرویس Realtime مصاحبه هنوز در دسترس نیست.",
      transport_timeout: "اتصال امن timeout شد.",
      transport_unavailable: "اتصال امن قطع شد.",
      reconnect_exhausted: "اتصال مجدد پس از تعداد تلاش مجاز موفق نشد.",
      session_expired: "نشست امن کاندیدای شما منقضی شده است.",
      consent_required: "رضایت لازم برای مصاحبه دیگر فعال نیست.",
      unexpected: "در اتصال مصاحبه خطای غیرمنتظره‌ای رخ داد.",
    },
    instructionsTitle: "در طول مصاحبه",
    instructions: [
      "تا زمانی که پاسخ در حال دریافت یا اتصال در حال بازیابی است این صفحه را باز نگه دارید.",
      "اگر شبکه قطع شد مصاحبه دوم شروع نکنید؛ به همین نشست امن متصل شوید.",
      "می‌توانید توضیح بیشتر بخواهید یا از پاسخ به یک سؤال صرف‌نظر کنید. تصمیم نهایی استخدام انسانی است.",
    ],
  },
} as const satisfies Record<AppLocale, unknown>;
