export enum InterviewWorkflowStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REVIEW = 'REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
