import Link from "next/link";
import { aiActivity, attentionItems, recommendedActions } from "../../lib/demo-data";
import { Icon } from "../../components/product/icon";
import { DemoNotice, MetricCard, Panel, PersonAvatar, SectionHeader, TinyTrend } from "../../components/product/recruiting-ui";

export default function CommandCenterPage(){return <div className="space-y-4">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-[24px] font-semibold tracking-tight text-slate-950">Good morning, Sara 👋</h1><p className="mt-1 text-[11px] text-slate-500">Here’s what’s happening with your hiring today.</p></div><DemoNotice/></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon="jobs" label="Open Jobs" value="24" note="6 open · 3 on hold"/><MetricCard icon="candidates" label="Active Candidates" value="342" note="+18 this week" tone="violet"/><MetricCard icon="interviews" label="Interviews Today" value="15" note="5 scheduled today" tone="indigo"/><MetricCard icon="briefcase" label="Offers" value="3" note="2 pending approval" tone="amber"/></div>
  <div className="grid gap-3 xl:grid-cols-[1.05fr_1fr_.95fr]">
    <Panel><SectionHeader title="Needs your attention" action={<Link href="/app/candidates" className="text-[9px] font-semibold text-indigo-600">View all (12)</Link>}/><div className="space-y-1 px-5 pb-5 pt-3">{attentionItems.map(([title,sub,tone],i)=><div key={title} className="flex items-start gap-3 rounded-[9px] px-2 py-2 hover:bg-slate-50"><div className={`mt-0.5 grid h-6 w-6 place-items-center rounded-[7px] ${tone==="violet"?"bg-violet-50 text-violet-600":tone==="blue"?"bg-blue-50 text-blue-600":tone==="green"?"bg-emerald-50 text-emerald-600":"bg-amber-50 text-amber-600"}`}><Icon name={i===0?"candidates":i===1?"interviews":i===2?"inbox":"target"} size={13}/></div><div><div className="text-[10px] font-medium text-slate-800">{title}</div><div className="mt-0.5 text-[9px] text-slate-400">{sub}</div></div></div>)}</div></Panel>
    <Panel><SectionHeader title="AI Recruiter activity" action={<span className="text-[9px] text-slate-400">This week⌄</span>}/><div className="space-y-2 px-5 pb-5 pt-3">{aiActivity.map(([title,note],i)=><div key={title} className="flex items-center gap-3 rounded-[9px] px-2 py-2"><div className="grid h-6 w-6 place-items-center rounded-[7px] bg-indigo-50 text-indigo-600"><Icon name={i===0?"candidates":i===1?"brain":i===2?"message":"interviews"} size={13}/></div><span className="flex-1 text-[10px] text-slate-700">{title}</span><span className="text-[8px] font-medium text-emerald-600">{note}</span></div>)}</div><div className="border-t border-slate-100 px-5 py-3 text-center text-[9px] font-semibold text-indigo-600">View full activity →</div></Panel>
    <Panel><SectionHeader title="Recommended actions"/><div className="space-y-2 px-5 pb-5 pt-3">{recommendedActions.map(([title,sub],i)=><div key={title} className="rounded-[10px] border border-slate-100 p-3"><div className="flex gap-2"><div className="grid h-6 w-6 place-items-center rounded-[7px] bg-indigo-50 text-indigo-600"><Icon name={i===0?"candidates":i===1?"target":"message"} size={13}/></div><div><div className="text-[10px] font-medium text-slate-800">{title}</div><div className="mt-1 text-[8px] text-slate-400">{sub}</div></div></div></div>)}</div></Panel>
  </div>
  <Panel><SectionHeader title="Upcoming" action={<span className="text-[9px] font-semibold text-indigo-600">View calendar</span>}/><div className="grid gap-2 p-5 pt-3 sm:grid-cols-2 xl:grid-cols-4">{[["Interview","Ali Rahimi","Today, 11:00 AM"],["Hiring Manager Review","Senior Backend Engineer","Today, 2:00 PM"],["Interview","Sara Mohammadi","Tomorrow, 10:00 AM"],["Job Approval","DevOps Engineer","Tomorrow, 3:00 PM"]].map(([kind,name,time],i)=><div key={name} className="flex gap-3 rounded-[10px] border border-slate-100 p-3"><div className="grid h-7 w-7 place-items-center rounded-[8px] bg-violet-50 text-violet-600"><Icon name={i===1?"jobs":"calendar"} size={13}/></div><div><div className="text-[8px] font-medium text-slate-400">{kind}</div><div className="mt-0.5 text-[10px] font-semibold text-slate-800">{name}</div><div className="mt-0.5 text-[8px] text-slate-400">{time}</div></div></div>)}</div></Panel>
  <Panel><SectionHeader title="Hiring pipeline overview" action={<span className="text-[9px] text-slate-400">This month⌄</span>}/><div className="grid gap-2 p-5 pt-3 sm:grid-cols-3 xl:grid-cols-6">{[["Applied","523","100%"],["Screening","132","25%"],["Interview","34","6.5%"],["Finalist","12","2.3%"],["Offered","3","0.6%"],["Hired","1","0.2%"]].map(([label,value,pct],i)=><div key={label} className="relative rounded-[10px] border border-slate-100 p-3"><div className="text-[8px] text-slate-400">{label}</div><div className="mt-1 flex items-end justify-between"><span className="text-[17px] font-semibold">{value}</span><TinyTrend up={i!==2}/></div><div className="mt-1 text-[8px] text-slate-400">{pct}</div><div className="mt-3 h-1 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-400 to-violet-400" style={{width:`${Math.max(8,100-i*17)}%`}}/></div></div>)}</div></Panel>
</div>}
