export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FAILED_LOGIN: 'FAILED_LOGIN',
  ROLE_CHANGED: 'ROLE_CHANGED',
  CANDIDATE_INVITED: 'CANDIDATE_INVITED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  INTERVIEW_FINISHED: 'INTERVIEW_FINISHED',
  SCORE_SUBMITTED: 'SCORE_SUBMITTED',
  AI_EXECUTION: 'AI_EXECUTION',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
