export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FAILED_LOGIN: 'FAILED_LOGIN',
  ROLE_CHANGED: 'ROLE_CHANGED',
  CANDIDATE_INVITED: 'CANDIDATE_INVITED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  SCORE_SUBMITTED: 'SCORE_SUBMITTED',
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
